DATASET: 
  TRAIN: 'encoder/outputs/vit_xlnet/train'
  VAL: 'encoder/outputs/vit_xlnet/test'
  GT: '/data/wushiwei/data/assistq/assistq_test/test_with_gt.json'
DATALOADER:
  NUM_WORKERS: 4
INPUT:
  QA: 'qa_maskx-1.pth'
  VIDEO: 'video.pth'
  SCRIPT: 'script.pth'
  PARA: 'paras.pth'
  DIM: 768
  NUM_MASKS: 1
MODEL:
  ARCH: 'q2a'
  DIM_STATE: 768
  NUM_HEADS: 1
  HISTORY: 
    TRAIN: 'gt'
    VAL: 'max'
    ARCH: 'gru'
  FUNCTION_CENTRIC: True
SOLVER:
  LR: 0.02
  BATCH_SIZE: 16
  WARMUP_EPOCHS: 0
  MAX_EPOCHS: 10
CHECK_VAL_EVERY_N_EPOCH: 1
NUM_GPUS: 1
CKPT: ''