DATASET: 
  ROOT: "/data/chenjoya/assistq"
  SPLIT: "train"
  LABEL: "train.json"
MODEL: 
  VISION: "vit_base_patch16_384"
  TEXT: "xlnet-base-cased"
INPUT: 
  FPS: 1
  SIZE: [384, 384]
FOR:
  VIDEO: False
  SCRIPT: False
  QA: False
  PARA: False
QA:
  NUM_MASKS: -1 # best performance